version: '3.9'

services:
  backend:
    container_name: 'backend'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/backend_config.env
    command: bash -c "cd /code/src/ && alembic upgrade head && uvicorn logic.main:server.app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    networks:
      - diploma_network
    depends_on:
      - postgres
    volumes:
      - ./:/code

  postgres:
    image: postgres:latest
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUT}:${POSTGRES_PORT_IN}
    networks:
      - diploma_network

volumes:
  postgres_volume: {}

networks:
  diploma_network:
    driver: "bridge"