services:
  backend:
    container_name: backend
    build:
      context: /backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/code
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    command: >
      bash -c "cd /code && alembic upgrade head && 
      uvicorn src.core.main:server.app --host 0.0.0.0 --port 8080 --reload"

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
